image: ruby:2.5.1

cache:
  paths:
    - vendor/

test:
  except:
    - tags
    - release
  script:
    - bundle
    - bundle exec rake

release:
  only:
    - release@getto-systems-labo/rubygens-params
  script:
    - ./bin/push_tags.sh
